<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.bingo789</groupId>
        <artifactId>bingo-parent</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>bingo-common</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>bingo-common-core</module>
        <module>bingo-common-web</module>
        <module>bingo-common-mybatis</module>
        <module>bingo-common-redis</module>
        <module>bingo-common-mq</module>
        <module>bingo-common-job</module>
        <module>bingo-common-obs</module>
    </modules>
</project>
